apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/amar-chand/argocd-jenkins.git
    targetRevision: HEAD
    path: argo-applications/customers/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      