apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-frontend-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/amar-chand/argocd-jenkins.git
    targetRevision: argocd
    path: argo-applications/web-frontend/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      