apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  selector:
    app: jenkins
  ports:
  - port: 50000
    targetPort: 50000
  type: ClusterIP
