apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customers
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
        - image: amarchanddargad/argo-customer-images:customers-8cc7c539cedcf8299cb6099c5d4c0aee17c34f59
          name: argo-customer-images
          ports:
            - containerPort: 3000
              name: customer-port
