apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customers
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
        - image: amarchanddargad/argo-images:customers-50c5201be2dd50cf41c7d9076170783c4e030232
          name: argo-customer-images
          resources: {}
status: {}
