apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customers
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
        - image: amarchanddargad/argo-customer-images:customers-a49e7fc252135b3cd5854814657d2e40b4876d04
          name: argo-customer-images
          resources: {}
status: {}
