apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-frontend
    spec:
      containers:
        - image: amarchanddargad/argo-web-frontend-images:web-frontend-a49e7fc252135b3cd5854814657d2e40b4876d04
          name: argo-web-frontend-images
          resources: {}
status: {}
